export const DEPARTMENTS = [
  'Agricultural and Environmental Engineering',
  'Civil and Environmental Engineering',
  'Electrical and Electronics Engineering',
  'Mechanical Engineering',
  'Mining Engineering',
  'Metallurgical and Materials Engineering',
  'Computer Science',
  'Information Technology',
  'Cyber Security',
  'Software Engineering',
  'Biochemistry',
  'Biology',
  'Chemistry',
  'Mathematics',
  'Microbiology',
  'Physics',
  'Science Laboratory Technology',
  'Statistics',
  'Architecture',
  'Estate Management',
  'Quantity Surveying',
  'Urban and Regional Planning',
  'Industrial Design',
  'Surveying and Geoinformatics',
  'Agricultural Economics and Extension',
  'Animal Production and Health',
  'Crop, Soil and Pest Management',
  'Fisheries and Aquaculture Technology',
  'Food Science and Technology',
  'Forestry and Wood Technology',
  'Ecotourism and Wildlife Management',
  'Applied Geology',
  'Applied Geophysics',
  'Meteorology and Climate Science',
  'Marine Science and Technology',
  'Remote Sensing and GIS',
  'Accounting',
  'Business Administration',
  'Economics',
  'Entrepreneurship Management Technology',
  'Industrial and Production Engineering',
  'Project Management Technology',
  'Transport Management Technology',
];

export const LEVELS = ['100', '200', '300', '400', '500', '600', '700', '800', '900'];

export const INTERESTS = [
  'Coding', 'Design', 'Music', 'Sports', 'Reading', 'Gaming', 'Photography',
  'Traveling', 'Cooking', 'Art', 'Movies', 'Dancing', 'Fitness', 'Tech',
  'Entrepreneurship', 'Volunteering', 'Fashion', 'Writing', 'Public Speaking',
  'Research', 'Networking', 'Startups', 'AI', 'Blockchain', 'Web3'
];

export const UI_TERMS = {
  interestSingular: 'Interest',
  interestPast: 'Interested',
  incomingInterestPlural: 'interests',
  likesRoute: '/likes',
} as const;
